modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/Akkiruk/catchrate-display/issues"

[[mods]]
modId="catchrate_display"
version="1.3.3"
displayName="Cobblemon Catch Rate Display"
description='''Shows real-time catch rate percentages during Cobblemon battles. Displays ball effectiveness, status bonuses, and HP impact. Works client-only with estimates, or install on server for 100% accurate calculations.'''
authors="Akkiruk"
logoFile="assets/catchrate-display/icon.png"
displayURL="https://modrinth.com/mod/catchrate-display"

[[dependencies.catchrate_display]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.catchrate_display]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.catchrate_display]]
modId="cobblemon"
type="required"
versionRange="[1.6.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.catchrate_display]]
modId="kotlinforforge"
type="required"
versionRange="[5.0.0,)"
ordering="NONE"
side="BOTH"
